### ISSUE TITLE
Should LICENSE be in root directory?

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [godot-nim/demo#21]
It probably should be in the creeps demo, and even then the art is from an existing source (and the code to some extent, I assume) which may have their own license. [EDIT](https://github.com/kidscancode/Godot3_dodge/blob/master/LICENSE): `Copyright (c) 2017 KidsCanCode`

I just had this thought as the templates particularly shouldn't require `copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software`.

**Comment by panno8M** [comment]
Certainly.

- [x] Delete the LICENSE in the root of demo
- [x] Copy the LICENSE in Dodge from KidsCanCode
- [x] Abandon my license notation
