### ISSUE TITLE
Execution in windows environment fails due to wrong path to dll file

### ISSUE THREAD

**Issue by panno8M** [godot-nim/demo#28]
godot-nim/gdext-nim#45

**Comment by insomniacUNDERSCORElemon** [comment]
Was simply changing the .gdextension files a temporary fix? I thought you were the one who added to prefix to .toDll, as I remember when there was no lib prefix.

This seems like an issue when someone isn't aware of the platform behavior difference.

**Comment by panno8M** [comment]
The toDll function is included in the nimscript standard library.

https://github.com/nim-lang/Nim/blob/702f8342ff6ebe612540628ca2a69a3ef9ec26d2/lib/system/nimscript.nim#L148-L150

The lack of prefix and extension was a side effect of using nimble for the build system. nimble does not have an option to make the dll the build target, so I had to force the dll by specifying --app:lib in config.nims.
