### ISSUE TITLE
add pausing and exiting functionality

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [godot-nim/demo#8]
How I got it working:

1. input map, new action: pause_game, p key
2. inside gdPlayer.nim, just before movement controls:   
  ```
  if self.Input.isActionPressed "ui_cancel":
    self.getTree.quit()
  if self.Input.isActionJustPressed "pause_game":
    self.get_tree().paused = not self.get_tree().paused
  if self.get_tree().paused == true: return
```
3. in editor, set player process mode to `always` (note the last line in the code above prevents paused movement).

Another alternate pause button could be the space bar. (EDIT: Bonus, WASD movement)

**Comment by insomniacUNDERSCORElemon** [comment]
I just want to add that I found the tutorial for this [in the Godot docs](https://docs.godotengine.org/en/3.0/getting_started/step_by_step/your_first_game.html), there's a gif showing that there's an after-image on the player. It is fine without it (personal preference), but it may be worth adding for parity.

Also it would be good to add a preview image to the creeps demo .md

**Comment by panno8M** [comment]
This is documentation from the 3.X era. gdextension users may be confusing since they will be referring to the 4.X documentation (and tutorials).

**Comment by insomniacUNDERSCORElemon** [comment]
I only linked to the docs to show the visual feature that I was talking about.

**Comment by panno8M** [comment]
That visual feature is only available in 3.X and may confuse users who compare it to the GDScript in 4.X.
Are you simply saying that a GIF of a working image should be included in the README?

**Comment by insomniacUNDERSCORElemon** [comment]
> That visual feature is only available in 3.X

Alright, I didn't know.

> Are you simply saying that a GIF of a working image should be included in the README?

Nope. Just saying a plain still screenshot of this version running like I did for mine. I can do this if you'd like, so long as it won't cause a file conflict with the .md. And it's also low priority.

**Comment by panno8M** [comment]
I don't know how they create the afterimage, but of course it can be achieved in 4.X. However, the Dodge the Creeps tutorial in 4.X does not have that process.

> I can do this if you'd like

Please do.
